import { config } from '../config/index.js';
import { logger } from './logger.js';

const PLACES_API_BASE = 'https://places.googleapis.com/v1';

export interface PlaceSuggestion {
  placeId: string;
  primaryText: string;
  secondaryText: string;
  types: string[];
}

export interface PlaceDetails {
  placeId: string;
  lat: number;
  lng: number;
  formattedAddress: string;
  name: string;
  neighborhood: string | null;
  city: string | null;
}

interface AutocompleteResponse {
  suggestions?: Array<{
    placePrediction?: {
      placeId?: string;
      structuredFormat?: {
        mainText?: { text?: string };
        secondaryText?: { text?: string };
      };
      types?: string[];
    };
  }>;
}

interface PlaceDetailsResponse {
  id?: string;
  location?: { latitude?: number; longitude?: number };
  formattedAddress?: string;
  displayName?: { text?: string };
  addressComponents?: Array<{
    longText?: string;
    types?: string[];
  }>;
}

function getApiKey(): string {
  const key = config.GOOGLE_MAPS_API_KEY ?? config.GOOGLE_PLACES_API_KEY;
  if (!key) {
    throw new Error('Google Maps API key is not configured');
  }
  return key;
}

/**
 * Call Google Places Autocomplete (New) API.
 * `sessionToken` should be a UUID generated by the client at the start of a search session
 * and reused for the corresponding Place Details call to take advantage of session-based pricing.
 *
 * `lat`/`lng` are optional — when absent we omit `locationBias` so Google
 * falls back to IP-based localization instead of biasing to (0, 0).
 */
export async function getPlaceAutocomplete(
  input: string,
  lat: number | undefined,
  lng: number | undefined,
  sessionToken: string,
  limit = 15
): Promise<PlaceSuggestion[]> {
  const apiKey = getApiKey();

  const body: Record<string, unknown> = {
    input,
    sessionToken,
    // No `includedRegionCodes` and no `includedPrimaryTypes` — return both
    // venues (`establishment`) and street addresses (`address` / `geocode`)
    // worldwide, so the search behaves like Google Maps.
    languageCode: 'en',
  };

  if (typeof lat === 'number' && typeof lng === 'number') {
    body['locationBias'] = {
      circle: {
        center: { latitude: lat, longitude: lng },
        radius: 30_000,
      },
    };
  }

  const start = Date.now();
  const response = await fetch(`${PLACES_API_BASE}/places:autocomplete`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Goog-Api-Key': apiKey,
    },
    body: JSON.stringify(body),
  });

  const latencyMs = Date.now() - start;
  logger.debug({ input, latencyMs }, 'Google Places Autocomplete call');

  if (!response.ok) {
    const text = await response.text();
    logger.warn(
      { status: response.status, body: text },
      'Google Places Autocomplete error'
    );
    return [];
  }

  const data = (await response.json()) as AutocompleteResponse;
  const suggestions = data.suggestions ?? [];

  return suggestions.slice(0, limit).flatMap((s) => {
    const p = s.placePrediction;
    if (!p?.placeId) {
      return [];
    }
    return [
      {
        placeId: p.placeId,
        primaryText: p.structuredFormat?.mainText?.text ?? '',
        secondaryText: p.structuredFormat?.secondaryText?.text ?? '',
        types: p.types ?? [],
      },
    ];
  });
}

/**
 * Call Google Place Details (New) API for a single place.
 * Must use the same `sessionToken` that was used for the preceding Autocomplete call.
 */
export async function getPlaceDetails(
  placeId: string,
  sessionToken: string
): Promise<PlaceDetails | null> {
  const apiKey = getApiKey();

  const start = Date.now();
  const response = await fetch(
    `${PLACES_API_BASE}/places/${encodeURIComponent(placeId)}?sessionToken=${encodeURIComponent(sessionToken)}`,
    {
      method: 'GET',
      headers: {
        'X-Goog-Api-Key': apiKey,
        'X-Goog-FieldMask': 'id,displayName,formattedAddress,location,addressComponents',
      },
    }
  );

  const latencyMs = Date.now() - start;
  logger.debug({ placeId, latencyMs }, 'Google Place Details call');

  if (!response.ok) {
    const text = await response.text();
    logger.warn(
      { placeId, status: response.status, body: text },
      'Google Place Details error'
    );
    return null;
  }

  const data = (await response.json()) as PlaceDetailsResponse;

  if (!data.location?.latitude || !data.location?.longitude) {
    return null;
  }

  const components = data.addressComponents ?? [];
  const neighborhood =
    findAddressComponent(components, 'sublocality_level_1') ??
    findAddressComponent(components, 'neighborhood') ??
    findAddressComponent(components, 'sublocality');
  const city =
    findAddressComponent(components, 'locality') ??
    findAddressComponent(components, 'administrative_area_level_1');

  return {
    placeId,
    lat: data.location.latitude,
    lng: data.location.longitude,
    formattedAddress: data.formattedAddress ?? '',
    name: data.displayName?.text ?? '',
    neighborhood: neighborhood ?? null,
    city: city ?? null,
  };
}

function findAddressComponent(
  components: PlaceDetailsResponse['addressComponents'],
  type: string
): string | undefined {
  return components?.find((c) => c.types?.includes(type))?.longText;
}
